import React from 'react';
import { useResearch } from '../../context/ResearchContext.tsx';
import {
  Compass,
  Sparkles,
  HelpCircle,
  Key,
  Layers,
  FlaskConical,
  Sliders,
  AlertOctagon,
  SearchCode,
  RefreshCw,
  Info
} from 'lucide-react';

export const PlannerView: React.FC = () => {
  const {
    activeProject,
    generateResearchPlan,
    isAILoading,
    activeProvider,
    activeModel
  } = useResearch();

  if (!activeProject) {
    return (
      <div className="text-center py-16 text-slate-400">
        No active research project selected.
      </div>
    );
  }

  const plan = activeProject.plan;

  return (
    <div className="max-w-5xl mx-auto space-y-6 pb-12">
      {/* Header bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-800 pb-4">
        <div>
          <div className="text-[10px] font-mono uppercase tracking-wider text-cyan-400">
            Phase 01 · Research Formulation
          </div>
          <h1 className="text-xl font-semibold text-white mt-0.5">
            Structured Research Planner
          </h1>
          <p className="text-xs text-slate-400 mt-1">
            Systematic formulation of objectives, subquestions, variables, and potential investigative gaps.
          </p>
        </div>

        <button
          onClick={generateResearchPlan}
          disabled={isAILoading}
          className="inline-flex items-center gap-2 bg-cyan-600 hover:bg-cyan-500 disabled:opacity-50 text-white text-xs font-medium px-4 py-2 rounded-md transition-colors shadow-sm self-start sm:self-auto"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${isAILoading ? 'animate-spin' : ''}`} />
          <span>{plan ? 'Regenerate Plan' : 'Generate Research Plan'}</span>
        </button>
      </div>

      {/* Mandatory Scholarly Label */}
      <div className="bg-amber-950/40 border border-amber-800/50 rounded-lg p-3.5 text-xs text-amber-200/90 flex items-start gap-2.5">
        <Info className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
        <div>
          <strong className="text-amber-300 uppercase tracking-wider text-[11px] block font-mono">
            Scholarly Notice: AI-Generated Investigative Suggestions
          </strong>
          <span className="text-amber-200/80">
            The items below are AI-synthesized research suggestions generated by {activeProvider.toUpperCase()} ({activeModel}) based on your question. They represent investigative hypotheses and conceptual frameworks, not established empirical facts.
          </span>
        </div>
      </div>

      {!plan ? (
        <div className="border border-slate-800 rounded-xl bg-slate-900/60 p-8 text-center space-y-3">
          <Compass className="w-10 h-10 text-cyan-400 mx-auto opacity-80" />
          <h3 className="text-base font-medium text-white">No Research Plan Generated Yet</h3>
          <p className="text-xs text-slate-400 max-w-md mx-auto leading-relaxed">
            Click below to generate a comprehensive academic research plan with objectives, subquestions, methodology possibilities, and variables to investigate.
          </p>
          <button
            onClick={generateResearchPlan}
            disabled={isAILoading}
            className="mt-2 bg-cyan-600 hover:bg-cyan-500 text-white text-xs font-medium px-5 py-2.5 rounded-md transition-colors inline-flex items-center gap-2"
          >
            <Sparkles className="w-4 h-4" />
            Generate Plan with {activeProvider.toUpperCase()}
          </button>
        </div>
      ) : (
        <div className="space-y-6">
          {/* Research Objective */}
          <div className="bg-slate-900 border border-slate-800 rounded-lg p-5">
            <div className="flex items-center gap-2 text-xs font-mono uppercase text-cyan-400 tracking-wider mb-2">
              <Compass className="w-4 h-4 text-cyan-400" />
              <span>Core Research Objective</span>
            </div>
            <p className="text-sm text-slate-100 leading-relaxed font-sans">
              {plan.researchObjective}
            </p>
            <div className="mt-3 text-[11px] text-slate-500 font-mono">
              Generated by: {plan.providerUsed} ({plan.modelUsed}) · {new Date(plan.generatedAt).toLocaleString()}
            </div>
          </div>

          {/* Subquestions & Keywords Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* Subquestions */}
            <div className="bg-slate-900 border border-slate-800 rounded-lg p-5 flex flex-col justify-between">
              <div>
                <div className="flex items-center gap-2 text-xs font-mono uppercase text-cyan-400 tracking-wider mb-3">
                  <HelpCircle className="w-4 h-4" />
                  <span>Research Subquestions</span>
                </div>
                <ul className="space-y-2.5">
                  {plan.subquestions.map((sq, i) => (
                    <li key={i} className="text-xs text-slate-300 flex items-start gap-2.5 leading-relaxed">
                      <span className="font-mono text-cyan-400 font-semibold text-[11px] shrink-0 mt-0.5">
                        Q{i + 1}.
                      </span>
                      <span>{sq}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            {/* Keywords */}
            <div className="bg-slate-900 border border-slate-800 rounded-lg p-5 flex flex-col justify-between">
              <div>
                <div className="flex items-center gap-2 text-xs font-mono uppercase text-cyan-400 tracking-wider mb-3">
                  <Key className="w-4 h-4" />
                  <span>Key Domain Nomenclature & Keywords</span>
                </div>
                <div className="flex flex-wrap gap-2">
                  {plan.importantKeywords.map((kw, i) => (
                    <span
                      key={i}
                      className="text-xs bg-slate-950 border border-slate-800 text-slate-300 px-2.5 py-1 rounded"
                    >
                      {kw}
                    </span>
                  ))}
                </div>
              </div>

              <div className="mt-4 pt-3 border-t border-slate-800 text-[11px] text-slate-500">
                Recommended for database indexing (IEEE Xplore, Google Scholar, ScienceDirect).
              </div>
            </div>
          </div>

          {/* Suggested Structure & Source Categories */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="bg-slate-900 border border-slate-800 rounded-lg p-5">
              <div className="flex items-center gap-2 text-xs font-mono uppercase text-cyan-400 tracking-wider mb-3">
                <Layers className="w-4 h-4" />
                <span>Suggested Report Structure</span>
              </div>
              <ol className="space-y-2 text-xs text-slate-300">
                {plan.suggestedStructure.map((sec, i) => (
                  <li key={i} className="flex items-center gap-2">
                    <span className="w-1.5 h-1.5 rounded-full bg-cyan-400 shrink-0" />
                    <span>{sec}</span>
                  </li>
                ))}
              </ol>
            </div>

            <div className="bg-slate-900 border border-slate-800 rounded-lg p-5">
              <div className="flex items-center gap-2 text-xs font-mono uppercase text-cyan-400 tracking-wider mb-3">
                <SearchCode className="w-4 h-4" />
                <span>Target Source Categories</span>
              </div>
              <ul className="space-y-2 text-xs text-slate-300">
                {plan.sourceCategories.map((cat, i) => (
                  <li key={i} className="flex items-center gap-2">
                    <span className="w-1.5 h-1.5 rounded-full bg-slate-600 shrink-0" />
                    <span>{cat}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* Methodology Possibilities & Variables */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="bg-slate-900 border border-slate-800 rounded-lg p-5">
              <div className="flex items-center gap-2 text-xs font-mono uppercase text-cyan-400 tracking-wider mb-3">
                <FlaskConical className="w-4 h-4" />
                <span>Methodology Possibilities</span>
              </div>
              <ul className="space-y-2 text-xs text-slate-300">
                {plan.methodologyPossibilities.map((m, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="text-cyan-400 font-mono text-[11px] shrink-0 mt-0.5">•</span>
                    <span>{m}</span>
                  </li>
                ))}
              </ul>
            </div>

            <div className="bg-slate-900 border border-slate-800 rounded-lg p-5">
              <div className="flex items-center gap-2 text-xs font-mono uppercase text-cyan-400 tracking-wider mb-3">
                <Sliders className="w-4 h-4" />
                <span>Variables to Investigate</span>
              </div>
              <ul className="space-y-2 text-xs text-slate-300">
                {plan.variablesToInvestigate.map((v, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="text-cyan-400 font-mono text-[11px] shrink-0 mt-0.5">•</span>
                    <span>{v}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* Potential Limitations & Gaps */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="bg-slate-900 border border-slate-800 rounded-lg p-5">
              <div className="flex items-center gap-2 text-xs font-mono uppercase text-amber-400 tracking-wider mb-3">
                <AlertOctagon className="w-4 h-4" />
                <span>Potential Experimental Limitations</span>
              </div>
              <ul className="space-y-2 text-xs text-slate-300">
                {plan.potentialLimitations.map((lim, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="text-amber-400 shrink-0 font-mono text-[11px] mt-0.5">▲</span>
                    <span>{lim}</span>
                  </li>
                ))}
              </ul>
            </div>

            <div className="bg-slate-900 border border-slate-800 rounded-lg p-5">
              <div className="flex items-center gap-2 text-xs font-mono uppercase text-amber-400 tracking-wider mb-3">
                <SearchCode className="w-4 h-4" />
                <span>Anticipated Research Gaps</span>
              </div>
              <ul className="space-y-2 text-xs text-slate-300">
                {plan.potentialResearchGaps.map((gap, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="text-amber-400 shrink-0 font-mono text-[11px] mt-0.5">▲</span>
                    <span>{gap}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
